In [2]:
import pandas as pd
import numpy as np
import bs4
import requests

In [2]:
url1='https://www.newlifesw.org.tw/index.php/zh/momney/donate/5941-111-2'
url2='https://www.newlifesw.org.tw/index.php/zh/momney/donate/5940-111-1'
url3='https://www.newlifesw.org.tw/index.php/zh/momney/donate/5896-110-12'
url4='https://www.newlifesw.org.tw/index.php/zh/momney/donate/5895-110-11'
url5='https://www.newlifesw.org.tw/index.php/zh/momney/donate/5823-110-10'
url6='https://www.newlifesw.org.tw/index.php/zh/momney/donate/5822-110-9'

headers=({
    'User-Agent':'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.109 Safari/537.36'
})

In [3]:
response=requests.get(url=url1,headers=headers)

root=bs4.BeautifulSoup(response.text,'html.parser')

table1 = root.find('table')

trs = table1.find_all('tr')[1:]
rows = list()
for tr in trs:
    rows.append([td.text for td in tr.find_all('td')])
    
Final1=pd.DataFrame(data=rows)

Final1

,0,1,2,3,4,5
0,捐款項目,贊助人,贊助金額,入帳日期,收據編號,備註
1,弱勢家庭服務,善心人士,500,111/02/01,11102003,
2,弱勢家庭服務,泰山扶輪社,"3,000",111/02/09,5874,
3,弱勢家庭服務,財團法人紅富善坊教育基金會,"5,000",111/02/09,11102006,
4,弱勢家庭服務,古萬富,300,111/02/09,11102007,
...,...,...,...,...,...,...
137,弱勢家庭服務,台灣銀髮族關懷推廣協會,"1,000",111/02/24,11102168,
138,弱勢家庭服務,羅素如,500,111/02/25,11102171,
139,弱勢家庭服務,極光先進光學股份有限公司,"50,000",111/02/25,11102172,
140,弱勢家庭服務,羅素如,10,111/02/25,11102176,
141,弱勢家庭服務,峻億貿易股份有限公司,"15,312",111/02/28,11102175,

In [4]:
response=requests.get(url=url2,headers=headers)

root=bs4.BeautifulSoup(response.text,'html.parser')

table2 = root.find('table')

trs = table2.find_all('tr')[1:]
rows = list()
for tr in trs:
    rows.append([td.text for td in tr.find_all('td')])
    
Final2=pd.DataFrame(data=rows)

Final2

,0,1,2,3,4,5
0,捐款項目,贊助人,贊助金額,入帳日期,收據編號,備註
1,弱勢家庭服務,正新鋁業股份有限公司 劉炳宏,"50,000",111/01/30,11101201,
2,弱勢家庭服務,戚蕙萍,"1,000",111/01/28,11101203,
3,弱勢家庭服務,陳明珠,"5,000",111/01/27,11101202,
4,弱勢家庭服務,萬兆生活科技有限公司 王莉靈,"20,000",111/01/27,11101198,
...,...,...,...,...,...,...
198,弱勢家庭服務,蘇妙枝,"1,000",111/01/03,11101004,
199,弱勢家庭服務,陳文龍.林群華.陳奕勻.陳禹衡,"1,000",111/01/03,11101002,
200,弱勢家庭服務,蒙德里安C棟,500,111/01/03,11101001,
201,弱勢家庭服務,善心人士,500,111/01/01,11101186,
202,弱勢家庭服務,遲勝德,"5,000",111/01/01,11012225,

In [5]:
response=requests.get(url=url3,headers=headers)

root=bs4.BeautifulSoup(response.text,'html.parser')

table3 = root.find('table')

trs = table3.find_all('tr')[1:]
rows = list()
for tr in trs:
    rows.append([td.text for td in tr.find_all('td')])
    
Final3=pd.DataFrame(data=rows)

Final3

,0,1,2,3,4,5
0,110.12捐款清冊,None,None,None,None,None
1,捐款項目,贊助人,贊助金額,入帳日期,收據編號,備註
2,弱勢家庭服務,萬兆生活科技有限公司 王木義,"20,000",110/12/01,11012001,
3,免費愛心餐,顏丞佐.塗秉璇,"5,000",110/12/01,11012002,
4,弱勢家庭服務,財團法人見賢思琪社會福利公益基金會,"10,000",110/12/07,11012003,
...,...,...,...,...,...,...
218,弱勢家庭服務,許榮華,"2,000",110/12/29,11012218,
219,弱勢家庭服務,胡家瑋,"4,000",110/12/29,11012218,
220,弱勢家庭服務,胡家綸,"4,000",110/12/29,11012218,
221,弱勢家庭服務,陳志偉,200,110/12/29,11012218,
222,弱勢家庭服務,新北市仁慧社福協進會,"10,066",110/12/29,11012218,

In [6]:
response=requests.get(url=url4,headers=headers)

root=bs4.BeautifulSoup(response.text,'html.parser')

table4 = root.find('table')

trs = table4.find_all('tr')[1:]
rows = list()
for tr in trs:
    rows.append([td.text for td in tr.find_all('td')])
    
Final4=pd.DataFrame(data=rows)

Final4

,0,1,2,3,4,5
0,110.11捐款清冊,None,None,None,None,None
1,捐款項目,贊助人,贊助金額,入帳日期,收據編號,備註
2,弱勢家庭服務,蕭孟君,"5,000",110/11/04,11011001,
3,弱勢家庭服務,楊政宏,515,110/11/01,11011002,
4,弱勢家庭服務,姜吳慧如,"5,000",110/11/01,11011003,
...,...,...,...,...,...,...
176,免費愛心餐,財團法人佛陀教育基金會,"5,000",110/11/29,11011177,
177,弱勢學子免費課後服務,財團法人佛陀教育基金會,"4,000",110/11/29,11011178,
178,弱勢家庭服務,李彥祥,"6,000",110/11/30,11011179,
179,弱勢學子免費課後服務,黃慰國,"5,000",110/11/29,11010180,
180,弱勢學子免費課後服務,澄運機械有限公司,"1,000",110/11/26,11010181,

In [7]:
response=requests.get(url=url5,headers=headers)

root=bs4.BeautifulSoup(response.text,'html.parser')

table5 = root.find('table')

trs = table5.find_all('tr')[1:]
rows = list()
for tr in trs:
    rows.append([td.text for td in tr.find_all('td')])
    
Final5=pd.DataFrame(data=rows)

Final5

          0           1                   2          3         4   5
0     捐款項目         贊助人                贊助金額       入帳日期       收據編號  備註
1    弱勢家庭服務     台北芝山扶輪社             120,000  110/10/28  11010170
2    弱勢家庭服務  大亮建築股份有限公司              30,000  110/10/28  11010175
3    弱勢家庭服務    台北市慈恩扶輪社              30,000  110/10/27  11010142
4    弱勢家庭服務   台滬晉國際有限公司              60,000  110/10/27  11010143
..      ...         ...                 ...        ...       ...  ..
173  弱勢家庭服務         陳靜璇                 100  110/10/04  11010121
174  弱勢家庭服務         陳幸妘                 100  110/10/04  11010122
175  弱勢家庭服務         劉信宏                 100  110/10/04  11010123
176  弱勢家庭服務         邱錦花                 200  110/10/04  11010124
177  弱勢家庭服務        善心人士                 500  110/10/01  11010179

[178 rows x 6 columns]

In [8]:
response=requests.get(url=url6,headers=headers)

root=bs4.BeautifulSoup(response.text,'html.parser')

table6 = root.find('table')

trs = table6.find_all('tr')[1:]
rows = list()
for tr in trs:
    rows.append([td.text for td in tr.find_all('td')])
    
Final6=pd.DataFrame(data=rows)

Final6

,0,1,2,3,4,5
0,,None,None,None,None,None
1,捐款項目,贊助人,贊助金額,入帳日期,收據編號,備註
2,弱勢家庭服務,帥哥美女，汪端霞,...,110/09/28,11009215,
3,弱勢家庭服務,陳柏嘉,...,110/09/27,11009183,
4,弱勢家庭服務,劉裕隆,...,110/09/27,11009184,
...,...,...,...,...,...,...
180,弱勢家庭服務,蔡欣霖,...,110/09/02,11009006,
181,弱勢家庭服務,王木義,...,110/09/02,11009007,帳號#955104893000
182,弱勢家庭服務,善心人士,...,110/09/01,11009218,
183,弱勢家庭服務,陳芊縈,...,11/09/13,11009040,
184,弱勢家庭服務,陳芊卉,...,11/09/13,11009041,

In [9]:
Final_collect=Final1.append(Final2).append(Final3).append(Final4).append(Final5).append(Final6)
Final_collect

,0,1,2,3,4,5
0,捐款項目,贊助人,贊助金額,入帳日期,收據編號,備註
1,弱勢家庭服務,善心人士,500,111/02/01,11102003,
2,弱勢家庭服務,泰山扶輪社,"3,000",111/02/09,5874,
3,弱勢家庭服務,財團法人紅富善坊教育基金會,"5,000",111/02/09,11102006,
4,弱勢家庭服務,古萬富,300,111/02/09,11102007,
...,...,...,...,...,...,...
180,弱勢家庭服務,蔡欣霖,...,110/09/02,11009006,
181,弱勢家庭服務,王木義,...,110/09/02,11009007,帳號#955104893000
182,弱勢家庭服務,善心人士,...,110/09/01,11009218,
183,弱勢家庭服務,陳芊縈,...,11/09/13,11009040,
184,弱勢家庭服務,陳芊卉,...,11/09/13,11009041,

In [10]:
Final_collect.to_csv('新生活捐近六月款芳名錄.csv',encoding='utf-8-sig')

In [4]:
Final_read=pd.read_csv('/Users/humphreyshen/Desktop/Visual Code/Crawler Practice/Crawler_Final/新生活捐近六月款芳名錄.csv')
Final_read

       筆次    捐款項目            贊助人    贊助金額       入帳日期      收據編號               備註
0       1  弱勢家庭服務           善心人士     500  111/02/01  11102003
1       2  弱勢家庭服務          泰山扶輪社   3,000  111/02/09      5874
2       3  弱勢家庭服務  財團法人紅富善坊教育基金會   5,000  111/02/09  11102006
3       4  弱勢家庭服務            古萬富     300  111/02/09  11102007
4       5  弱勢家庭服務            古芷伃     100  111/02/09  11102008
...   ...     ...            ...     ...        ...       ...              ...
1098  180  弱勢家庭服務            蔡欣霖   1,000  110/09/02  11009006
1099  181  弱勢家庭服務            王木義  20,000  110/09/02  11009007  帳號#955104893000
1100  182  弱勢家庭服務           善心人士     500  110/09/01  11009218
1101  183  弱勢家庭服務            陳芊縈     600  2011/9/13  11009040
1102  184  弱勢家庭服務            陳芊卉     600  2011/9/13  11009041

[1103 rows x 7 columns]

In [10]:
Final_item=Final_read.groupby('捐款項目')
Final_item.size()

捐款項目
免費愛心餐           34
弱勢學子免費課後服務      42
弱勢家庭服務        1026
急難救助金            1
dtype: int64

In [12]:
Final_money=Final_read.groupby('贊助金額')
Final_money.size().sort_values()

贊助金額
16,000       1
314,614      1
515          1
20,416       1
4,900        1
          ...
3,000       66
2,000       77
500         93
1,000      196
300        267
Length: 66, dtype: int64

In [13]:
Final_unit=Final_read.groupby('贊助人')
Final_unit.size()

贊助人
N-ART     1
丁于倢       1
京壐有限公司    1
何佳儒       1
何佳娟       1
         ..
黃瑋琳       1
黃維敏       1
黃美蓉       1
黃翠香       1
黃連發       6
Length: 467, dtype: int64